name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'                  
      - 'app.py'                  
      - 'Dockerfile*'              
      - 'pyproject.toml'          
      - 'uv.lock'                 
      - 'models/**'               
      - '.github/workflows/ci.yml' 
  pull_request: 
    branches: [ main ]
  workflow_dispatch: 

jobs:
  test-and-scan-code:
    name: Unit Test & Code/Dependency Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies & Run tests
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv
          source .venv/bin/activate
          uv pip install -r requirements.txt
          uv pip install pytest pytest-cov
          mkdir -p data/processed/
          cp tests/dummy_data/* data/processed/
          PYTHONPATH=. pytest tests/ --cov=src --cov-report=xml

      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-scan-and-push:
    name: Build, Trivy Scan & Push Images
    needs: test-and-scan-code
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::770353436964:role/github-actions-cicd-oidc-mlops-housing-project-role
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # ---- API IMAGE ----
      - name: Build housing-api
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: housing-api
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile .

      - name: Run Trivy scanner on housing-api
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ steps.login-ecr.outputs.registry }}/housing-api:${{ github.sha }}'
          format: 'table'
          exit-code: '0' 
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Push housing-api to ECR
        if: github.event_name != 'pull_request'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: housing-api
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # ---- UI IMAGE ----
      - name: Build housing-ui
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: housing-ui
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile.streamlit .

      - name: Run Trivy scanner on housing-ui
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ steps.login-ecr.outputs.registry }}/housing-ui:${{ github.sha }}'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Push housing-ui to ECR
        if: github.event_name != 'pull_request'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: housing-ui
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  # AUTO UPDATE REPO GITOPS
  update-gitops-repo:
    name: Update Image Tags in GitOps Repo
    needs: build-scan-and-push
    if: github.event_name != 'pull_request' # Chỉ chạy khi push code thật sự
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitOps Repository
        uses: actions/checkout@v4
        with:
          repository: 'khaipd18/Development-and-Deployment-of-a-Housing-Price-Prediction-System-using-MLOps-GitOps' 
          token: ${{ secrets.GITOPS_PAT }} 
          path: gitops-repo

      - name: Update Image Tags via yq
        run: |
          cd gitops-repo
          
          # Dùng công cụ yq (có sẵn trên ubuntu-latest) để sửa tag trong file values-dev.yaml
          yq -i '.image.tag = "${{ github.sha }}"' app/overlays/dev/api/values-dev.yaml
          yq -i '.image.tag = "${{ github.sha }}"' app/overlays/dev/ui/values-dev.yaml
          
          # (Tùy chọn) Nếu bạn muốn push thẳng lên Prod thì thêm 2 dòng này
          # yq -i '.image.tag = "${{ github.sha }}"' app/overlays/prod/api/values-prod.yaml
          # yq -i '.image.tag = "${{ github.sha }}"' app/overlays/prod/ui/values-prod.yaml

      - name: Commit and Push changes
        run: |
          cd gitops-repo
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          
          git add .
          # Chỉ commit nếu có sự thay đổi
          git diff --quiet && git diff --staged --quiet || git commit -m "ci: update image tags to ${{ github.sha }} [skip ci]"
          git push origin main